table 01_Medidas
	lineageTag: aaaa01a1-8d77-450d-84ba-0b6634ec199c

	measure 'Base de Datos' = COUNT(input_majo_puro[ID_KEY_MAJO])
		formatString: 0
		lineageTag: 7acfe8bd-0ac3-424f-a3d7-94729e8364ee

	measure Contactados = COUNT(output[ID_KEY_OUT])
		formatString: 0
		lineageTag: 44c2a1f5-0702-486b-a5df-5d4761ee3c29

	measure 'Cortaron Comunicación' =
			
			CALCULATE(
			    COUNT(output[Interactores]),
			    FILTER(output, output[Interactores] = "No")
			    )
		formatString: 0
		lineageTag: 9211e164-cf91-4a86-b97f-9ffe850e90dc

	measure 'Interactuaron con Luz' =
			
			CALCULATE(
			    COUNT(output[Interactores]),
			    FILTER(output, output[Interactores] = "Sí")
			    )
		formatString: 0
		lineageTag: 8d0b0671-b26b-44a9-b843-53f29be16314

	measure 'Solicitaron Conexión' =
			
			CALCULATE(
			    COUNT(output[Confirmo Solucion]),
			    FILTER(output, output[Interactores] = "Sí"),
			    FILTER(output, output[Confirmo Solucion] = "Sí")
			    )
		formatString: 0
		lineageTag: a854a3ad-8269-4c76-ae14-6eadb4ded2ce

	measure 'Avisarán al Normalizar' =
			
			CALCULATE(
			    COUNT(output[Confirmo Solucion]),
			    FILTER(output, output[Interactores] = "Sí"),
			    FILTER(output, output[Confirmo Solucion] = "No")
			    )
		formatString: 0
		lineageTag: 0e01eaeb-648b-4b26-9534-76afdf5f9420

	measure '% Avisarán al Normalizar' = [Avisarán al Normalizar] / [Base de Datos]
		lineageTag: 6a0b7201-07a4-495e-a039-3fdc69e2e960

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Contactados' = [Contactados] / [Base de Datos]
		lineageTag: b5d44373-8ee4-4787-8176-6226c0205200

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Interactuaron con Luz' = [Interactuaron con Luz] / [Base de Datos]
		lineageTag: 33aaa5fd-49ea-4eb8-bdd2-0ecbea38f274

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Cortaron Comunicación' = [Cortaron Comunicación] / [Base de Datos]
		lineageTag: 5996edb8-f3d6-4717-91f4-66e6cbe1289c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Solicitaron Conexión' = [Solicitaron Conexión]/[Base de Datos]
		lineageTag: 70180eb9-b697-4ada-b51f-728e92930843

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Sentimiento Positivo/Neutral' =
			VAR TotalValidos = CALCULATE(
			    COUNT(output[Sentimiento Cliente]),
			    output[Sentimiento Cliente] <> "-"
			)
			VAR TotalPositivosNeutrales = CALCULATE(
			    COUNT(output[Sentimiento Cliente]),
			    output[Sentimiento Cliente] IN {"Positivo", "Neutral"}
			)
			RETURN DIVIDE(TotalPositivosNeutrales, TotalValidos, 0)
		formatString: 0.0%
		lineageTag: f1e2d3c4-b5a6-7890-abcd-ef1234567890

	measure '% Interrupciones (Barge-in)' =
			VAR TotalValidos = CALCULATE(
			    COUNT(output[Interrupcion Al Bot]),
			    output[Interrupcion Al Bot] <> "-"
			)
			VAR TotalInterrupciones = CALCULATE(
			    COUNT(output[Interrupcion Al Bot]),
			    output[Interrupcion Al Bot] = "Sí"
			)
			RETURN DIVIDE(TotalInterrupciones, TotalValidos, 0)
		formatString: 0.0%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-012345678901

	measure '% Carga al 0800' =
			VAR TotalValidos = CALCULATE(
			    COUNT(output[Menciona 0800]),
			    output[Menciona 0800] <> "-"
			)
			VAR TotalMenciones = CALCULATE(
			    COUNT(output[Menciona 0800]),
			    output[Menciona 0800] = "Sí"
			)
			RETURN DIVIDE(TotalMenciones, TotalValidos, 0)
		formatString: 0.0%
		lineageTag: b2c3d4e5-f6a7-8901-bcde-123456789012

	measure 'Fricción - Segundos Iniciales' =
			CALCULATE(
			    COUNT(output[Interactores]),
			    output[Interactores] = "No",
			    output[Motivo No Entrega] = "corta la llamada"
			)
		formatString: 0
		lineageTag: c3d4e5f6-a7b8-9012-cdef-234567890123

	measure 'Fricción - Antes de completar el mensaje' =
			CALCULATE(
			    COUNT(output[Interactores]),
			    output[Interactores] = "No",
			    output[Motivo No Entrega] IN {"error técnico", "interrupciones"}
			)
		formatString: 0
		lineageTag: d4e5f6a7-b8c9-0123-def0-345678901234

	measure 'Fricción - Buzón de Voz / Contestador' =
			CALCULATE(
			    COUNT(output[Interactores]),
			    output[Interactores] = "No",
			    output[Motivo No Entrega] = "contestador"
			)
		formatString: 0
		lineageTag: e5f6a7b8-c9d0-1234-ef01-456789012345

	measure 'Fricción - Otras Causas' =
			CALCULATE(
			    COUNT(output[Interactores]),
			    output[Interactores] = "No",
			    NOT(output[Motivo No Entrega] IN {"corta la llamada", "error técnico", "interrupciones", "contestador"})
			)
		formatString: 0
		lineageTag: f6a7b8c9-d0e1-2345-f012-567890123456

	/// Versión histórica (acumulado total). Inmune al filtro del segmentador de fecha vía REMOVEFILTERS(DimCalendario).
	measure 'Base de Datos (Histórico)' = CALCULATE([Base de Datos], REMOVEFILTERS(DimCalendario))
		formatString: 0
		lineageTag: 1a000001-0000-4000-8000-000000000001

	measure 'Contactados (Histórico)' = CALCULATE([Contactados], REMOVEFILTERS(DimCalendario))
		formatString: 0
		lineageTag: 1a000002-0000-4000-8000-000000000002

	measure 'Cortaron Comunicación (Histórico)' = CALCULATE([Cortaron Comunicación], REMOVEFILTERS(DimCalendario))
		formatString: 0
		lineageTag: 1a000003-0000-4000-8000-000000000003

	measure 'Interactuaron con Luz (Histórico)' = CALCULATE([Interactuaron con Luz], REMOVEFILTERS(DimCalendario))
		formatString: 0
		lineageTag: 1a000004-0000-4000-8000-000000000004

	measure 'Solicitaron Conexión (Histórico)' = CALCULATE([Solicitaron Conexión], REMOVEFILTERS(DimCalendario))
		formatString: 0
		lineageTag: 1a000005-0000-4000-8000-000000000005

	measure 'Avisarán al Normalizar (Histórico)' = CALCULATE([Avisarán al Normalizar], REMOVEFILTERS(DimCalendario))
		formatString: 0
		lineageTag: 1a000006-0000-4000-8000-000000000006

	/// Porcentajes históricos: numerador y denominador inmunes a la fecha, devuelven la proporción sobre la base total acumulada.
	measure '% Contactados (Histórico)' = CALCULATE([% Contactados], REMOVEFILTERS(DimCalendario))
		formatString: 0.0%
		lineageTag: 1b000001-0000-4000-8000-000000000011

	measure '% Cortaron Comunicación (Histórico)' = CALCULATE([% Cortaron Comunicación], REMOVEFILTERS(DimCalendario))
		formatString: 0.0%
		lineageTag: 1b000002-0000-4000-8000-000000000012

	measure '% Interactuaron con Luz (Histórico)' = CALCULATE([% Interactuaron con Luz], REMOVEFILTERS(DimCalendario))
		formatString: 0.0%
		lineageTag: 1b000003-0000-4000-8000-000000000013

	measure '% Solicitaron Conexión (Histórico)' = CALCULATE([% Solicitaron Conexión], REMOVEFILTERS(DimCalendario))
		formatString: 0.0%
		lineageTag: 1b000004-0000-4000-8000-000000000014

	measure '% Avisarán al Normalizar (Histórico)' = CALCULATE([% Avisarán al Normalizar], REMOVEFILTERS(DimCalendario))
		formatString: 0.0%
		lineageTag: 1b000005-0000-4000-8000-000000000015

	/// Desglose de sentimiento por volumen sobre la base de respuestas válidas (excluye "-" y vacíos). Mismo patrón que las medidas de Fricción.
	measure 'Sentimiento - Positivo' =
			CALCULATE(
			    COUNT(output[Sentimiento Cliente]),
			    output[Sentimiento Cliente] = "Positivo"
			)
		formatString: 0
		lineageTag: 2c000001-0000-4000-8000-000000000021

	measure 'Sentimiento - Neutral' =
			CALCULATE(
			    COUNT(output[Sentimiento Cliente]),
			    output[Sentimiento Cliente] = "Neutral"
			)
		formatString: 0
		lineageTag: 2c000002-0000-4000-8000-000000000022

	measure 'Sentimiento - Negativo' =
			CALCULATE(
			    COUNT(output[Sentimiento Cliente]),
			    output[Sentimiento Cliente] <> "-",
			    NOT(output[Sentimiento Cliente] IN {"Positivo", "Neutral"})
			)
		formatString: 0
		lineageTag: 2c000003-0000-4000-8000-000000000023

	/// Promedios históricos de duración de habla en minutos (Seg / 60). Inmunes al filtro de fecha vía REMOVEFILTERS(DimCalendario).
	measure 'Promedio Histórico Tiempo Cliente (MM:ss)' = ```
			
			VAR PromedioSegundos = 
			    CALCULATE(
			        AVERAGE(output[Tiempo Habla Cliente Seg]),
			        REMOVEFILTERS(DimCalendario)
			    )
			
			VAR Minutos = TRUNC(PromedioSegundos / 60)
			VAR Segundos = ROUND(MOD(PromedioSegundos, 60), 0)
			
			RETURN
			    IF(
			        NOT ISBLANK(PromedioSegundos),
			        FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00"),
			        BLANK()
			    )
			```
		lineageTag: 3a000001-0000-4000-8000-000000000031

	measure 'Promedio Histórico Tiempo Luz (MM:ss)' = ```
			
			VAR PromedioSegundos = 
			    CALCULATE(
			        AVERAGE(output[Tiempo Habla Bot Seg]),
			        REMOVEFILTERS(DimCalendario)
			    )
			
			VAR Minutos = TRUNC(PromedioSegundos / 60)
			VAR Segundos = ROUND(MOD(PromedioSegundos, 60), 0)
			
			RETURN
			    IF(
			        NOT ISBLANK(PromedioSegundos),
			        FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00"),
			        BLANK()
			    )
			```
		lineageTag: 3a000002-0000-4000-8000-000000000032

	/// Conteo de registros por Impedimento y su proporción sobre el total (para el Top 5 de impedimentos).
	measure 'Conteo Impedimento' = COUNT(output[Impedimento])
		formatString: 0
		lineageTag: 3b000001-0000-4000-8000-000000000033

	measure '% Impedimento' =
			DIVIDE(
			    [Conteo Impedimento],
			    CALCULATE([Conteo Impedimento], REMOVEFILTERS(output[Impedimento]))
			)
		formatString: 0.0%
		lineageTag: 3b000002-0000-4000-8000-000000000034

	column Dummy
		lineageTag: 40d71262-83ef-4e63-a3f3-e261057cbe42
		summarizeBy: none
		isNameInferred
		sourceColumn: [Dummy]

		annotation SummarizationSetBy = Automatic

	partition 01_Medidas = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Dummy", STRING,
				    {
				        {""}
				    }
				)

	annotation PBI_Id = c8993b6d658e45698f016e20849e0005

